### ISSUE TITLE
Object life360.0.info.connection seems to be of invalid type

### ISSUE THREAD

**Issue by Wildbill-Z** [MiGoller/ioBroker.life360#14]
After start/restart, I allways get this warn message:
Object life360.0.info.connection is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
Seems that the object is of wrong type. Maybe Life360-server sends status "true/false" as string an not boolean. I manually changed type in iobroker to "string" and no more messages, everything seems to work fine.

**Comment by MiGoller** [comment]
Hey @Wildbill-Z ,

sorry for responding so lately. Do you still encounter the mentioned exception? If so, please give version 0.2.8 a try. You can install it from Github. I'll publish to npmjs later.

KR,
Michael

**Comment by Wildbill-Z** [comment]
Hi @MiGoller 
since I changed manually I never had the message again. Nevertheless I updated from 0.4.4 to 0.2.8 without a problem.
I'll close the issue. Thanks.

Greetings, Jürgen

**Comment by MiGoller** [comment]
Hi @Wildbill-Z ,

thank you for your feedback.

KR,
Michael
