### ISSUE TITLE
Error TypeError: Cannot read property 'sourceId' of null since update to 0.2.8

### ISSUE THREAD

**Issue by Wildbill-Z** [MiGoller/ioBroker.life360#18]
After updating to version 0.2.8 I get some errors in the log now and then (sometimes minutes between, sometimes hours). Here is one of the errors messages, they allways are exactly the same:

```
life360.0 | 2020-08-24 04:56:50.913 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
life360.0 | 2020-08-24 04:56:50.913 | error | at runMicrotasks (<anonymous>)
life360.0 | 2020-08-24 04:56:50.913 | error | at publishCircle (/opt/iobroker/node_modules/iobroker.life360/lib/life360DbConnector.js:664:5)
life360.0 | 2020-08-24 04:56:50.913 | error | at publishCirclePlaces (/opt/iobroker/node_modules/iobroker.life360/lib/life360DbConnector.js:697:103)
life360.0 | 2020-08-24 04:56:50.913 | error | (31940) TypeError: Cannot read property 'sourceId' of null
life360.0 | 2020-08-24 04:56:50.913 | error | (31940) unhandled promise rejection: Cannot read property 'sourceId' of null
Unhandled | 2020-08-24 04:56:50.912 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

The line with "Unhandled" is part of the error, it is allways the first one of such a error block.
Adapter seems to restart by itself and seems to do the job, but something seems wrong anyway.

Greetings, Jürgen

**Comment by MiGoller** [comment]
Hey @Wildbill-Z ,

looks like there is a member without any location-information at all. Didn't know that Life360 will push location-information for such members.

Well, I'll fix that issue and add some error handling.

Thank you for your feedback.

KR,
Michael

**Comment by MiGoller** [comment]
Hey @Wildbill-Z ,

I added some more error handling and some validators for the Life360 data. Right now I cannot raise that error anymore. Can you give it a try, please? You should bei able to install version 0.2.10 from GitHub or npmjs.

Please let me know, if it's working now.

Good luck.

KR,
Michael

**Comment by Wildbill-Z** [comment]
@MiGoller 
Updated without problem. Now we'll see if there are still any errors in the log.

Greetings, Jürgen

**Comment by MiGoller** [comment]
Hey @Wildbill-Z ,

ok, now we know that your wife's member data is missing when she's not at home. I'm sorry for tagging this event as a warning; it should be tagged for silly logging, only.

I'll fix that, because that message level is really annoying.

KR,
Michael

**Comment by MiGoller** [comment]
Hey @Wildbill-Z ,

please install version 0.2.11 from GitHub or npmjs and let me know if you still encounter "new" error or warning messages.

I added a switch at the instance's settings page (admin UI) to enable verbose logging, but it's disabled by default.


KR,
Michael

**Comment by Wildbill-Z** [comment]
@MiGoller Updated without problem. Seems like there are no more log messages. I'll close the issue.

Greetings
