### ISSUE TITLE
Adapter looses places (connection)

### ISSUE THREAD

**Issue by Starter4711** [MiGoller/ioBroker.life360#27]
**Describe the bug**  
Adapter looses places and deletes them, get them back ... repeat

**To Reproduce**  
nothing

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.2.12
 - JS-Controller version: 3.2.16
 - Node version: 12.22.0
 - Operating system: raspi light

**Additional context**  
https://forum.iobroker.net/topic/25631/neuer-adapter-life360/127

**Comment by MiGoller** [comment]
I'm able to reproduce the issue when Life360 API does not provide any information regarding Life360 places. I'll disable the automatic removal of related objects and datapoints.

**Comment by Starter4711** [comment]
Perfect THX
I dont think they are deleted, only the values.

**Comment by MiGoller** [comment]
Right. Only the values get removed if the API does not provide any information about the places. The places in Life360 will still exist until you delete them in the app.

Sadly to say that the API will respond with different information regarding to the endpoints behind their load balancers. There was as similar issue as few weeks ago.

**Comment by MiGoller** [comment]
@Starter4711 , please try version 0.2.14 from the npm registry or by installing by Github link.

**Comment by MiGoller** [comment]
Hey. Please confirm if the bugfix does the job. ;-)

**Comment by MiGoller** [comment]
Fixed with v0.2.14

**Comment by Starter4711** [comment]
Hi, never had a problem again, thx.

**Comment by MiGoller** [comment]
Thx for feedback.
