### ISSUE TITLE
Failed to create datapoint id [...] Ids are not allowed to end in "."

### ISSUE THREAD

**Issue by ppb1308** [MiGoller/ioBroker.life360#37]
In protocol section of iobroker i can see many error messages from Life260 adapter, all stating that a datapoint id can not be created with ending point ("."), can you please adjust the adapter to avoid this errorts?

ioBroker was updated completly today, but errors have been there before too.
ioBroker 3.1.11 is running on NUC with ProxMox in a Linux lxc with Ubuntu 19.10.

Error Messages look like:
Failed to create datapoint id "myplaces.Aaaa.Bbbb." with definition { _id: 'myplaces.Aaaa.Bbbb.', type: 'channel', common: { name: 'Bbbb.', desc: 'Bbbb. @ Aaaa' }, native: {}}: Error: The id "myplaces.Aaaa.Bbbb." is invalid. Ids are not allowed to end in "."

Thank yoiu in advance,
Peter

**Comment by MiGoller** [comment]
Hey @ppb1308 , do you have set name for people in Life360 with a trailig "."? Can you tell me the version of the Life360 adapter you have currently installed, please?

**Comment by ppb1308** [comment]
Hi @MiGoller ,
sorry for my late reply.
No, i have not set any Name with trailing ".", i have set firstname and surename, but in iOS App i see only firstname.

I am using last available beta version of adapter which is: 0.2.12 (1~)

i am running on lates js-controller on Ubuntu based on ProxMox on NUC.

**Comment by MiGoller** [comment]
Ok, please give the current release (v.0.2.15) a try. I had to sanitize some strings before converting them to object ids.

You can just install the current version from custom URL https://github.com/MiGoller/ioBroker.life360/ within the ioBroker Admin UI.

Please let me know if the messages will have gone away. Good luck.

KR, MiGoller

**Comment by MiGoller** [comment]
Will close this issue because I got no feedback after releasing 0.2.15.
