### ISSUE TITLE
JS Controller 3.3 - Wrong Type

### ISSUE THREAD

**Issue by Schmakus** [MiGoller/ioBroker.life360#42]
life360.0 | 2021-08-11 20:14:48.834 | info | (20493) State value to set for "life360.0.places.5d2c3cb7-f718-4956-aa00-86558a4bcede.gps-coordinates" has to be type "text" but received type "string"
-- | -- | -- | --
life360.0 | 2021-08-11 20:14:48.834 | info | (20493) State value to set for "life360.0.places.586c8370-970b-49f1-9b5f-82d2c02f7000.gps-coordinates" has to be type "text" but received type "string"

JSController 3.3

**Comment by jaschkopf** [comment]
I have the same issue. life360 adapter spams my logfile:
<html>
<body>


life360.0 | 2021-08-24 11:55:35.268 | info | (6299) State value to set for "life360.0.places.e1705b3d-d959-4fac-822c-e65fba6d3307.gps-coordinates" has to be type "text" but received type "string"
-- | -- | -- | --
life360.0 | 2021-08-24 11:55:35.267 | info | (6299) State value to set for "life360.0.places.d8bbac63-9f6a-4a86-92f3-2ba7ab30b775.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:55:35.264 | info | (6299) State value to set for "life360.0.places.c6041f6b-b47f-40f9-8dd3-bf39ec9bbf3f.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:55:35.263 | info | (6299) State value to set for "life360.0.places.9b1c037d-a6fd-4e06-a445-9ea494ae0756.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:55:35.259 | info | (6299) State value to set for "life360.0.places.120cea7f-92d7-4fe5-8a36-c606798be61a.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:55:33.213 | warn | (6299) Read-only state "life360.0.info.connection" has been written without ack-flag with value "true"
life360.0 | 2021-08-24 11:54:34.252 | info | (6299) State value to set for "life360.0.places.e1705b3d-d959-4fac-822c-e65fba6d3307.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:54:34.205 | info | (6299) State value to set for "life360.0.places.d8bbac63-9f6a-4a86-92f3-2ba7ab30b775.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:54:34.205 | info | (6299) State value to set for "life360.0.places.c6041f6b-b47f-40f9-8dd3-bf39ec9bbf3f.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:54:34.205 | info | (6299) State value to set for "life360.0.places.9b1c037d-a6fd-4e06-a445-9ea494ae0756.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:54:34.205 | info | (6299) State value to set for "life360.0.places.120cea7f-92d7-4fe5-8a36-c606798be61a.gps-coordinates" has to be type "text" but received type "string"
life360.0 | 2021-08-24 11:53:34.295 | info | (6299) State value to set for "life360.0.places.e1705b3d-d959-4fac-822c-e65fba6d3307.gps-coordinates" has to be type "text" but received type "string"


</body>
</html>

js-controller: 3.3.14/15 (issues with both versions)
Adapter version: 0.2.11

**Comment by MiGoller** [comment]
Hey @Schmakus,
hey @jaschkopf ,

thank you for your feedback. This looks like a known issue that has been fixed in later releases.

Please upgrade to v0.2.16 and let me know if you'll still encounter the mentioned warnings.

KR,
MiGoller

**Comment by jaschkopf** [comment]
I have updated straight from github to version 0.2.15 and the warnings are still there. After deleting all objects and restarting the adapter the info entry's are gone. 

How do I update to 0.2.16? These are the warnings i still get: 

<html>
<body>


life360.0 | 2021-08-25 10:55:03.332 | warn | Read-only state "life360.0.info.connection" has been written without ack-flag with value "true"
-- | -- | -- | --
life360.0 | 2021-08-25 10:51:03.298 | warn | Read-only state "life360.0.info.connection" has been written without ack-flag with value "true"
life360.0 | 2021-08-25 10:47:03.225 | warn | Read-only state "life360.0.info.connection" has been written without ack-flag with value "true"
life360.0 | 2021-08-25 10:43:03.331 | warn | Read-only state "life360.0.info.connection" has been written without ack-flag with value "true"
life360.0 | 2021-08-25 10:39:03.347 | warn | Read-only state "life360.0.info.connection" has been written without ack-flag with value "true"


</body>
</html>

**Comment by Schmakus** [comment]
Same as me. Update to 0.2.15

**Comment by MiGoller** [comment]
Hey,

I'm sorry. Version 0.2.16 is not available in the `master` branch right now; I still have got to merge it.

Please try to install the version 0.2.16 with the following URL: https://github.com/MiGoller/ioBroker.life360/tree/develop .

KR, MiGoller

**Comment by jaschkopf** [comment]
Thank you. I have installed it and will report if the errors are gone. looks good for now

**Comment by Schmakus** [comment]
Looks good with v0.2.16. Thanks.

**Comment by MiGoller** [comment]
I'll merge it into `master` asap and will let you know. Subscribe to the ioBroker forum thread https://forum.iobroker.net/topic/32718/test-adapter-life360-v0-2-x-github-npm, please, to receive information about upcoming and new releases.

**Comment by jaschkopf** [comment]
Everything fine. Thank you 💪
