### ISSUE TITLE
V 0.2.16 warnung no places found

### ISSUE THREAD

**Issue by guergen1** [MiGoller/ioBroker.life360#44]
Obwohl die Option "Life360 Places verarbeiten" abgewählt ist und kein Places-Adapter existiert, kommt im Log die Warnmeldung, dass keine Places gefunden werden.

V0.2.16
js-controller: 3.3.18
NPM: 6.14.15
Node.js: 12.22.6

**Comment by MiGoller** [comment]
Kein Ding. Dann habe ich zwei Punkte in demselben Code-Abschnitt.
