### ISSUE TITLE
Keine Sonderzeichen möglich

### ISSUE THREAD

**Issue by guergen1** [MiGoller/ioBroker.life360#47]
Der Adapter nimmt im Passwort keine Sonderzeichen, in der App ist das möglich, also sollte es hier auch möglich sein.

**Comment by guergen1** [comment]
Sorry... nicht drauf geachtet...
Ich habe ganz normale Sonderzeichen im Passwort gehabt, deutsche Tastatur, Raute und die Shift-Zeichen der Zahlen

**Comment by MiGoller** [comment]
Kannst Du mir sagen, ob Du konkret deutsche Umlaute im Kennwort hast?

**Comment by guergen1** [comment]
Deutsche Umlaute hatte ich keine

**Comment by MiGoller** [comment]
Ok, danke. Ich kann es nicht nachstellen. Habe diverse Sonderzeichen und Umlaute des deutschen Tastaturlayouts getestet. Keine Probleme in der App und beim Adapter.

Besteht die Möglichkeit, dass Du mir mal bitte die Sonderzeichen nennst, die Du nutzt?

**Comment by guergen1** [comment]
Klar:
!
&
#

Von Unterwegs gesendet

**Comment by MiGoller** [comment]
Möglicherweise habe ich einen Ansatz gefunden. Bist Du bereit, eine Entwicklerversion des Adapters zu testen? Dann würde ich das vorab implementieren, dass Du es testen könntest. Das wäre kein öffentliches Release!

**Comment by guergen1** [comment]
Klar, kann ich machen!

**Comment by MiGoller** [comment]
Danke. Dann könntest Du jetzt einmal die Version v0.2.17 von https://github.com/MiGoller/ioBroker.life360/tree/develop über den GitHub "Button" auf dem "Adapter Panel" mittels "Benutzerdefiniert" installieren.
![image](https://user-images.githubusercontent.com/1272642/142782776-31e04a9e-7694-4f49-8f1e-a3be5069bfa3.png)

Danach zur Sicherheit bitte einmal die Instanz des Adapters neu startet bzw. vorher noch einmal das Kennwort samt der Sonderzeichen in der Konfiguration des Adapters setzen. In meinen Tests funktionieren jetzt die von Dir genannten Zeichen. ;-) Es sollte jetzt alle Zeichen nutzbar sein, die auf einer deutschen Tastatur zu finden sind. Für russische, koreanische, etc. Schriftzeichen... naja, müsste mal jemand testen. ;-)

**Comment by guergen1** [comment]
Läuft mit "meinen" Sonderzeichen!

**Comment by MiGoller** [comment]
Klasse. Danke für das Feedback. Dann geht der Bugfix jetzt in das öffentliche Release v0.2.17 rein; das wird identisch mit dem sein, das Du installiert hast. Für die 0.2.18er Version musst Du dann aber bitte wieder von der Github Adresse https://github.com/MiGoller/ioBroker.life360/ (ohne `develop` ...) installieren. Sorry, dass das so umständlich ist.

**Comment by guergen1** [comment]
Kein Problem mit dem installieren, was willst du denn testen lassen in 0.2.18?

**Comment by MiGoller** [comment]
Das steht noch nicht fest. ;-) Erstmal muss das 0.2.17 raus, dass alle ein paar Fehler und Warnungen weniger haben. Parallel habe ich noch den Xplora-Adapter für die Smartwatches für Kinder.
