### ISSUE TITLE
Connection established but failed to authenticate. Check your credentials

### ISSUE THREAD

**Issue by theb3nzi** [MiGoller/ioBroker.life360#59]
adapter shows at once: „Connection established but failed to authenticate. Check your credentials“ i think you had to update the adapter. it didn't work until 2 p.m. today.

thanks

**Comment by RkcCorian** [comment]
Same for me... started today

**Comment by morphygee** [comment]
same issue

**Comment by MiGoller** [comment]
Looks like any authentication against the Life360 API fails. I can reproduce the issue with command line tools, too.

I'm sorry but I have to check for changes of the API. Please be patient.

**Comment by MiGoller** [comment]
Right now I'm unable to login to the Life360 app installed on my mobile device. The app denies the login due to wrong credentials. But if I try to reset my password (forgot password) the mobile browser returns an error 503 service unavailable.

Can you confirm?

**Comment by TomasiDeveloping** [comment]
Update:
![IMG_20220608_224825.jpg](https://user-images.githubusercontent.com/67390491/172714385-00502539-86bd-4c96-94c8-3a22bf17b9a3.jpg)

**Comment by theb3nzi** [comment]
The App is working for me 🤷🏻‍♂️

**Comment by morphygee** [comment]
https://twitter.com/Life360/status/1534636130317963265

**Comment by jfla76** [comment]
> Glad to hear about that. I can not login to app again after I logged out.

Hi, Same for me , i'm logged with email adress and error on login

I'm reloged with phone number and it's OK now

JF

**Comment by stefanoklett** [comment]
Ich wurde verrückt, als ich versuchte herauszufinden, warum es nicht funktionierte.

**Comment by RkcCorian** [comment]
It is working now again via App. Still the adapter is not working for me. Anything that I can do or do we simply have to wait longer? Many thanks!

**Comment by MiGoller** [comment]
Hey. I could get the mobile app working again, too. I'm sorry, but you'll have to be patient: The API endpoints have changed and the authorization process looks a bit different to the previous process. 

I'm still investigating but I the login succeeds again the Life360 API in my lab. Please be patient.

**Comment by MiGoller** [comment]
I am able to successfully authenticate against the Life360 API and to receive data regarding circles, places and members. I'll modify the adapter code, too. Keep calm, please. Shouldn't take to much time.

**Comment by MiGoller** [comment]
Dear all. I've just published the bugfix. Please update the adapter to v0.2.18 with the sources from the GitHub repository https://github.com/MiGoller/ioBroker.life360. I've updated the npm-package as well.

The installation or update might take up to some minutes, so please be patient. I'll investigate on that issue later on.

**Please update the adater instance's credentials before you start the instance after updating the adapter, please.**

Good luck and let me know if the fix does the job.

**Comment by theb3nzi** [comment]
Works PERFEKT! Thanks a lot for your work!

**Comment by jfla76** [comment]
Hi, Don't work for me

i have removed instance and plugin

I reinstalled from  https://github.com/MiGoller/ioBroker.life360

i put my user and password

i get this message  in log:

life360.0 | 2022-06-11 10:18:11.705 | warn | No data received from Life360 cloud services!
-- | -- | -- | --
life360.0 | 2022-06-11 10:18:11.704 | debug | Pushing cloud_data to callback function
life360.0 | 2022-06-11 10:18:11.703 | error | Error: Error: Connection established but failed to authenticate. Check your credentials!
life360.0 | 2022-06-11 10:18:11.701 | error | Failed to connect or to login for 6 times. Aborting ...
life360.0 | 2022-06-11 10:18:11.697 | info | Waiting for online operations to finish ...
life360.0 | 2022-06-11 10:18:11.694 | debug | Auth tokens deleted.
life360.0 | 2022-06-11 10:18:11.694 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2022-06-11 10:18:11.215 | debug | Connecting to Life360 service  ...
life360.0 | 2022-06-11 10:18:11.203 | debug | Not authenticated against Life360. Will try to connect ...
life360.0 | 2022-06-11 10:18:11.199 | info | Waiting for online operations to finish ...
life360.0 | 2022-06-11 10:18:11.197 | debug | Auth tokens deleted.
life360.0 | 2022-06-11 10:18:11.196 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2022-06-11 10:18:10.663 | debug | Connecting to Life360 service  ...
life360.0 | 2022-06-11 10:18:10.663 | debug | Not authenticated against Life360. Will try to connect ...
life360.0 | 2022-06-11 10:18:10.658 | info | Waiting for online operations to finish ...
life360.0 | 2022-06-11 10:18:10.616 | debug | Connecting to Life360 service  ...
life360.0 | 2022-06-11 10:18:10.610 | debug | Not authenticated against Life360. Will try to connect ...
life360.0 | 2022-06-11 10:18:10.555 | info | Waiting for online operations to finish ...
life360.0 | 2022-06-11 10:18:10.552 | debug | Auth tokens deleted.
life360.0 | 2022-06-11 10:18:10.551 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2022-06-11 10:18:10.092 | debug | Connecting to Life360 service  ...
life360.0 | 2022-06-11 10:18:10.091 | debug | Not authenticated against Life360. Will try to connect ...
life360.0 | 2022-06-11 10:18:10.088 | info | Waiting for online operations to finish ...
life360.0 | 2022-06-11 10:18:10.086 | debug | Auth tokens deleted.
life360.0 | 2022-06-11 10:18:10.086 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2022-06-11 10:18:09.613 | debug | Connecting to Life360 service  ...
life360.0 | 2022-06-11 10:18:09.612 | debug | Not authenticated against Life360. Will try to connect ...
life360.0 | 2022-06-11 10:18:09.607 | info | Waiting for online operations to finish ...
life360.0 | 2022-06-11 10:18:09.576 | debug | Auth tokens deleted.
life360.0 | 2022-06-11 10:18:09.575 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2022-06-11 10:18:08.945 | info | Polling enabled every 60 seconds.
life360.0 | 2022-06-11 10:18:08.929 | debug | Connecting to Life360 service  ...
life360.0 | 2022-06-11 10:18:08.927 | debug | Not authenticated against Life360. Will try to connect ...
life360.0 | 2022-06-11 10:18:08.924 | debug | Fetching Life360 cloud data ...
life360.0 | 2022-06-11 10:18:08.870 | info | starting.  Version 0.2.18 (non-npm:  MiGoller/ioBroker.life360#56ba15fa07202fdfa5c99420deaa03829e1a8178) in  /opt/iobroker/node_modules/iobroker.life360, node: v14.19.0,  js-controller: 4.0.19
life360.0 | 2022-06-11 10:18:08.596 | debug | States connected to redis: 127.0.0.1:9000
life360.0 | 2022-06-11 10:18:08.543 | debug | States create User PubSub Client
life360.0 | 2022-06-11 10:18:08.536 | debug | States create System PubSub Client
life360.0 | 2022-06-11 10:18:08.476 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
life360.0 | 2022-06-11 10:18:08.329 | debug | Objects connected to redis: 127.0.0.1:9001
life360.0 | 2022-06-11 10:18:08.306 | debug | Objects client initialize lua scripts
life360.0 | 2022-06-11 10:18:08.245 | debug | Objects create User PubSub Client
life360.0 | 2022-06-11 10:18:08.243 | debug | Objects create System PubSub Client
life360.0 | 2022-06-11 10:18:08.240 | debug | Objects client ready ... initialize now
life360.0 | 2022-06-11 10:18:08.189 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by theb3nzi** [comment]
You sure that your name/password is really correct? the new version still works great for me...

**Comment by barnie1989** [comment]
also for me it's working fine. I had only installed the ne version

**Comment by morphygee** [comment]
V0.2.18 from git works

**Comment by Horgul123** [comment]
Works for me. Thanks!

**Comment by MiGoller** [comment]
@jfla76 Hmm... looks like Life360 has disabled your account like mine. But don't worry, please try the following steps to reactivate your account.

1. Try to login with your countrycode and phonenumber instead of your email-address. Just enter your countrycode without the `+` and your phonenumber at the settings-page of the adapter's instance. Clear the email-address in the settings, too. Finally clear and enter again your password. Restart the adapter's instance at level `debug`.

2. If the adapter is able to login with your phonenumber, switch back to the email-address in the settings. Clear coountrycode and phonenumber and leave your password untouched. Restart the adapter's instance once more.

3. If it fails at all, please reset your account's password with the mobile app. Login using your mobile app first. If you can authenticate the mobile app, use the same set of credentials for the adapters. It's worth to say that you have to authenticate your mobile app first, because the app provides a unique key for your account.

Life360 invented a lot of changes to the API like new endpoints, unique device IDs, new authentication headers, new bearer tokens, etc. . I think I'll apply some more modifications to the code to keep the adapter working.

**Comment by Airwave1981** [comment]
> @jfla76 Hmm... looks like Life360 has disabled your account like mine. But don't worry, please try the following steps to reactivate your account.
> 
> 1. Try to login with your countrycode and phonenumber instead of your email-address. Just enter your countrycode without the `+` and your phonenumber at the settings-page of the adapter's instance. Clear the email-address in the settings, too. Finally clear and enter again your password. Restart the adapter's instance at level `debug`.
> 2. If the adapter is able to login with your phonenumber, switch back to the email-address in the settings. Clear coountrycode and phonenumber and leave your password untouched. Restart the adapter's instance once more.
> 3. If it fails at all, please reset your account's password with the mobile app. Login using your mobile app first. If you can authenticate the mobile app, use the same set of credentials for the adapters. It's worth to say that you have to authenticate your mobile app first, because the app provides a unique key for your account.
> 
> Life360 invented a lot of changes to the API like new endpoints, unique device IDs, new authentication headers, new bearer tokens, etc. . I think I'll apply some more modifications to the code to keep the adapter working.

Same issue here with v0.2.17 (should i go dev branch?).

Tried upper steps, but result is: <html>
<body>


Connection established but failed to authenticate. Check your credentials!
--
 

<br class="Apple-interchange-newline">
</body>
</html>

Tried also with zeros in countrycode (0049) and without (49)
and with starting zero at phone number (0....) and without and in combination with countrycode zeros and without.
And also with password change and email.

**Comment by MiGoller** [comment]
@Airwave1981 , @jfla76 Life360 has invented some changes to the API that let the adapter fail to login. You'll have to update to version `0.2.18` to get the adapter working again. 

Just install a new adapter in the ioBroker Admin UI using the GitHub URL https://github.com/MiGoller/ioBroker.life360. Due to a bug of `npm` v6 the installation process can last up to 10 to 30 minutes. Please be patient. 

But you can install the adapter from https://www.npmjs.com/package/iobroker.life360. Execute the following command in the iobroker root directory (e.g. in `/opt/iobroker`):

```shell
npm install iobroker.life360
```

**Comment by Airwave1981** [comment]
Great thank you, works with v0.2.18 via npm install iobroker.life360

**Comment by TomasiDeveloping** [comment]
Installation via GitHub link.
Start adapter everything fine.
@MiGoller best thanks for your efforts

**Comment by jfla76** [comment]
> @jfla76 Hmm... looks like Life360 has disabled your account like mine. But don't worry, please try the following steps to reactivate your account.
> 
>     1. Try to login with your countrycode and phonenumber instead of your email-address. Just enter your countrycode without the `+` and your phonenumber at the settings-page of the adapter's instance. Clear the email-address in the settings, too. Finally clear and enter again your password. Restart the adapter's instance at level `debug`.
> 
>     2. If the adapter is able to login with your phonenumber, switch back to the email-address in the settings. Clear coountrycode and phonenumber and leave your password untouched. Restart the adapter's instance once more.
> 
>     3. If it fails at all, please reset your account's password with the mobile app. Login using your mobile app first. If you can authenticate the mobile app, use the same set of credentials for the adapters. It's worth to say that you have to authenticate your mobile app first, because the app provides a unique key for your account.
> 
> 
> Life360 invented a lot of changes to the API like new endpoints, unique device IDs, new authentication headers, new bearer tokens, etc. . I think I'll apply some more modifications to the code to keep the adapter working.

Thanks, MiGoller

Work now 

I reseted password with phone , login on app on phone, 

Then login on adapter Life360 iobroker

JF

**Comment by RkcCorian** [comment]
Working for me as well! Thx!!!
