### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by ges7881** [MiGoller/ioBroker.life360#63]
Hi,

ich bekomme in letzter Zeit vermehrt Fehler vom Adapter:
![image](https://user-images.githubusercontent.com/106393937/176828813-da45066b-092f-4299-bc7c-9e6accb3dbbe.png)

Ist das ein Bug oder mach ich was falsch?

Könnte das am node.js 16 liegen?

Grüße

**Comment by MiGoller** [comment]
Hey @ges7881 ,

danke für das Feedback. `EAI_AGAIN` Fehler deuten auf Probleme mit der Namensauflösung (DNS-Server) hin (vgl. https://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html).

Hast Du einen Proxy-Server im Einsatz oder vielleicht eigene DNS-Server im Router gesetzt? Ich sehe die Fehler bei mir in den Logs nicht. Kannst Du ggf. auf Deinem Router in den Protokollen mal nachschauen, ob dort auch hinweise auf DNS-Fehler zu finden sind? VoIP ist dafür z.B. anfällig; das würdest Du im Protokoll sehen.

Viele Grüße,
MiGoller

**Comment by MiGoller** [comment]
Hallo. Gibt es hier neue Erkenntnisse? VG
