### ISSUE TITLE
"Connection established but failed to authenticate. Check your credentials!" are back.

### ISSUE THREAD

**Issue by Rushmed** [MiGoller/ioBroker.life360#67]
Hi sir.

Since some days the adapter is not able to connect l360 cloud service.

<html>
<body>

life360.0 | 2023-01-02 21:49:16.811 | warn | No data received from Life360 cloud services!
-- | -- | -- | --
life360.0 | 2023-01-02 21:49:16.811 | error | Error: Error: Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:49:16.810 | error | Failed to connect or to login for 6 times. Aborting ...
life360.0 | 2023-01-02 21:49:16.808 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:49:16.806 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:49:16.713 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:49:16.711 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:49:16.615 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:49:16.614 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:49:16.505 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:49:16.502 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:49:16.292 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:49:16.291 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:49:16.076 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:49:16.074 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:17.301 | warn | No data received from Life360 cloud services!
life360.0 | 2023-01-02 21:48:17.301 | error | Error: Error: Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:17.300 | error | Failed to connect or to login for 6 times. Aborting ...
life360.0 | 2023-01-02 21:48:17.299 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:48:17.297 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:17.098 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:48:17.096 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:16.814 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:48:16.813 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:16.601 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:48:16.600 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:16.330 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:48:16.328 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:48:16.100 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:48:16.096 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.485 | warn | No data received from Life360 cloud services!
life360.0 | 2023-01-02 21:47:16.484 | error | Error: Error: Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.484 | error | Failed to connect or to login for 6 times. Aborting ...
life360.0 | 2023-01-02 21:47:16.482 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:47:16.480 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.394 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:47:16.392 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.306 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:47:16.304 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.222 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:47:16.220 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.138 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:47:16.136 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:47:16.025 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:47:16.021 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.573 | warn | No data received from Life360 cloud services!
life360.0 | 2023-01-02 21:46:16.572 | error | Error: Error: Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.571 | error | Failed to connect or to login for 6 times. Aborting ...
life360.0 | 2023-01-02 21:46:16.569 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:46:16.567 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.470 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:46:16.467 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.364 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:46:16.362 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.271 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:46:16.269 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.164 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:46:16.162 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:16.064 | info | Waiting for online operations to finish ...
life360.0 | 2023-01-02 21:46:16.056 | error | Connection established but failed to authenticate. Check your credentials!
life360.0 | 2023-01-02 21:46:15.872 | info | Polling enabled every 60 seconds.
life360.0 | 2023-01-02 21:46:15.813 | info | starting. Version 0.2.18 (non-npm: MiGoller/ioBroker.life360#56ba15fa07202fdfa5c99420deaa03829e1a8178) in /opt/iobroker/node_modules/iobroker.life360, node: v16.19.0, js-controller: 4.0.24
host.Smartazamba | 2023-01-02 21:46:13.114 | info | instance system.adapter.life360.0 started with pid 812777

</body>
</html>

Everything was working fin until all of a sudden this warnings start to appear.
Tried to reenter login credentials.
Also tried phone number and countrycode login instead of mailadress.

**Comment by MiGoller** [comment]
Hey @Rushmed , please see my reply to your post on https://forum.iobroker.net/post/920919 . I'm really interested in the adapter's version you have installed.

**Comment by Rushmed** [comment]
Hi.
As u can see in the log I`m on 0.2.18.
Thanks in fruther for investigating my issue!

**Comment by MiGoller** [comment]
Ah, you're right. Sorry, didn't see that. Please update your adapter instance to `v0.2.19`. Did you install the adapter from GitHub or with `npm`? Do it the same way again for the current version `0.2.19`, please. The installation will update your instance, too.

**Comment by Rushmed** [comment]
Thanks! v0.2.19 fucked off the issue. Everything is working fine.
