### ISSUE TITLE
Authentifizierung schlägt fehl ...

### ISSUE THREAD

**Issue by Pauli29** [MiGoller/ioBroker.life360#68]
Der Adapter kann sich plötzlich nicht mehr anmelden obwohl die Zugangsdaten nicht geändert wurden.

**Comment by MiGoller** [comment]
Guten Morgen. Nutzt Du die Version `v0.2.19` des Adapters? Falls nicht, dann aktualisiere bitte auf diese Version; es gab ein paar Veränderungen bei Life360, auf die ich mit einer neuen Version reagieren musste.

**Comment by Pauli29** [comment]
Danke für den Hinweis.
Ich hatte nicht bedacht, dass der Adapter ja über GitHub installiert wurde und daher die automatischen Updates nicht funktionieren.
Jetzt kann er sich wieder verbinden.

Schönen Sonntag!

Beste Grüße

Paul Reinhart
________________________________
Von: MiGoller ***@***.***>
Gesendet: Sonntag, 22. Jänner 2023 10:23
An: MiGoller/ioBroker.life360
Cc: Pauli29; Author
Betreff: Re: [MiGoller/ioBroker.life360] Authentifizierung schlägt fehl ... (Issue #68) 

Guten Morgen. Nutzt Du die Version v0.2.19 des Adapters? Falls nicht, dann aktualisiere bitte auf diese Version; es gab ein paar Veränderungen bei Life360, auf die ich mit einer neuen Version reagieren musste.

**Comment by MiGoller** [comment]
Vielen Dank für das Feedback.
