### ISSUE TITLE
Connection established but failed to authenticate. Check your credentials!

### ISSUE THREAD

**Issue by ChristophsMowL** [MiGoller/ioBroker.life360#71]
Bekomme in unregelmäßigen Abständen diesen Fehler.
Habe Version 0.2.19 installiert. Kann ich da etwas tun?

Vielen Dank

**Comment by MiGoller** [comment]
Hey @ChristophsMowL , leider tritt das immer mal wieder auf: Anmeldeversuche werden von der Life360 API trotz korrekter Anmeldeinformationen sporadisch abgelehnt. Bislang konnte ich noch nicht herausfinden, ob z.B. die Anzahl der Anfragen darauf Einfluss hat oder nicht. Laut Feedback von Nutzern kommt es sporadisch zu diesem Verhalten unabhängig vom Aktualisierungsinterval, etc. . Derzeit wüsste ich, was Du tun könntest. Sorry.

**Comment by MiGoller** [comment]
Hallo @ChristophsMowL  und @ali86x , ich habe eine Idee, dass der "Fehler" nur als solcher angezeigt wird, wenn die Anmeldung nach "x" Versuchen wirklich nicht funktioniert. Die Realität zeigt, dass die Anmeldung vorübergehend immer mal wieder nicht funktioniert. Ich bitte noch um ein wenig Geduld, aber es ist in Arbeit. VG

**Comment by ChristophsMowL** [comment]
Hi @MiGoller 
vielen Dank für die Antwort! Ich habe immer mal wieder Verbindungsprobleme und seit heute habe ich keine Connection mehr. Nach 6 Versuchen wird abgebrochen

**Comment by ali86x** [comment]
Hallo zusammen. 
Selbes Problem hier. 
Seit heute funktioniert der Adapter auch bei mir nicht mehr. 
Log ist voll mit Fehlern und Anwesenheit etc wird nicht mehr erfasst.

**Comment by der-raab** [comment]
Hallo,
Bei mir das gleiche Problem.
Nach 6 Versuchen wird abgebrochen.

**Comment by MiGoller** [comment]
Hallo zusammen, entweder hat Life360 Probleme mit den Servern (s. https://m.facebook.com/story.php?story_fbid=pfbid02r7PRTXUQZqPxmq6vYuDeTgXAnyBwxJ9BCYyrdpMCQtRMYcRvdFFH3r9cB7rLGhel&id=100071883871666), oder es gibt wieder Änderungen an der API. Ich prüfe das, so schnell es geht.

**Comment by Bleiki68** [comment]
Hallo Zusammen,
seit gestern um 01:45 Uhr habe ich auch das problem. Life360 App funktioniert einwandfrei; der iobroker Adapter wirft im Log nur Fehler (Check credentials).
Dank Euch fürs kümmern....!

**Comment by ali86x** [comment]
Adapter über GitHub updaten und das Problem ist weg.

**Comment by ChristophsMowL** [comment]
Lovely. Vielen Dank @MiGoller

**Comment by Haui74** [comment]
Seit heute Nacht ist das Problem wieder da :(

**Comment by MiGoller** [comment]
Die aktuelle Version 0.2.22 kann im ioBroker per `npm` oder über GitHub installiert bzw. aktualisiert werden.
