### ISSUE TITLE
Connection established but failed to authenticate. Check your credentials!

### ISSUE THREAD

**Issue by BeSiRe1** [MiGoller/ioBroker.life360#78]
Leider verbindet sich der Adapter nicht mehr.

error: life360.0 (114935) Connection established but failed to authenticate. Check your credentials!

Adapterversion: 0.2.21
Nodejs: v18.17.1

**Comment by MiGoller** [comment]
Hey @BeSiRe1 , right now I can't confirm the issue, but I'm still investigating on that report.

Please stop the adapter instance, review your settings and start the adapter again. Try to login with your email address, please, if the adapter still fails.

BTW: Did you upgrade your ioBroker instance or your Node.js setup?

**Comment by BeSiRe1** [comment]
Hey, habe die Instanz gestoppt und alles überprüft. Bin schon immer mit meiner Email Adresse eingeloggt.
Ja habe gestern sowohl Node.js aktualisiert auf v18.17.1, wie auch den js-controller auf 5.0.12.

**Comment by MiGoller** [comment]
Ok, dann bitte einmal die Anmeldeinformationen (E-Mail-Adresse und Kennwort) neu eingeben und speichern. Nicht, dass hier jetzt das Kennwort nach dem Update mit einer anderen ioBroker-Instanz-ID entschlüssekt wird... dann passt es nicht mehr.

Du hast nicht zufällig vor dem Update ein Backup gemacht oder in der Vergangenheit mal die Settings der Adapterinstanz exportiert? Beim Import würde das Kennwort dann auch wieder richtig gesetzt.

Noch eine Frage: Du hast Controller und Node.js aktualisiert, aber es handelt sich nicht um ein Container (Docker) Setup, oder? Ggf. musst Du den Adapter deinstallieren und neu installieren. Ich stelle meinen ioBroker nach einem Update auf eine neue Node.js Version immer komplett aus einem Backup wieder her.

**Comment by BeSiRe1** [comment]
Also eine Neuinstallation des Adapters hat geholfen. Beszen dank für die Hilfe.
Wie sichere ich den Adapter am sinnvollsten?
Backitup sichert bei mir.
Mein ioBroker läuft als Container in Proxmox.(da mache ich natürlich auch Backups)

**Comment by MiGoller** [comment]
Hey, mit Container meinst Du das [Docker-Image von Buanet](https://hub.docker.com/r/buanet/iobroker/) oder einen LXC-Container mit "manueller" Installation des ioBrokers im Container? Für das Backup macht es m.E. eigentlich kaum Unterschiede außer vielleicht bei REDIS, etc. . Das soll ja alles auch zeitpunktgleich integer sein (vgl. "Snapshot"). 

Ich sichere meine Instanzen (Prod, Test und Dev) mit dem Backitup-Adapter; damit lässt sich der ioBroker nach einer Migration auf eine neue Major-Version oder auch bei Upgrades von Node.js, etc. gut wiederherstellen. Etwas fummelig wird es, wenn Du REDIS als State-DB, Zigbee, etc. nutzt, da dann noch weitere Daten gesichert werden müssen. Liegen die alle auf demselbem Host (oder im selben Container), dann geht das auch noch. Sonst musst Du Dir ggf. ein Host-übergreifendes Backup-Skript basteln, das alles berücksichtigt. Mir ist aber kein generisches Skript dazu bekannt, da es sehr auf Deine individuelle Umsetzung ankommt.

Ziel des ioBroker Backups sollte doch sein, dass die Gebäudesteuerung nach einer Fehlfunktion oder -Konfiguration, nach einem geplanten Upgrade und nach einem Totalverlust so schnell wie möglich wieder einsatzbereit ist. Meine Erfahrung ist, dass es in solchen "Stresssituationen" extrem nachhaltig ist, wenn ich vorher die Dinge so simpel wie möglich gehalten habe; da muss nicht alles im Top-Design realisiert sein: Die Kiste muss so schnell wie möglich wieder laufen.

In Deinem Fall könnte es hilfreich sein, statt Deinen produktiven Container zu aktualisieren, einen neuen, z.B. mit einer neuen Node.js Version, parallel aufzubauen und den ioBroker darin leer zu installieren. Der "neue" ioBroker startet parallel zum alten Container und kommt dem nicht in die Quere; der alte ioBroker läuft aber noch, also hast Du keinen Ausfall. Anstatt den neuen ioBroker jetzt wieder manuell zu konfigurieren, spielst Du das letzte Backup vom "alten" ioBroker ein. Dabei werden nicht nur die Objekte, States, Zigbee-Datenbanken, etc. wiederhergestellt, sondern auch **alle** Adapter-Instanzen, die auf Deinem alten ioBroker vorhanden sind, neu installiert. Bei einem Node.js Update ist die Wahrscheinlichkeit hoch, dass Du mit frisch installieren Adaptern dann auch nur ganz wenige Probleme, wenn überhaupt, haben solltest. Das Installieren der Adapter kann auf einer energieeffizienten Hardware schonmal zwischen 30 und 40 Minuten dauern. Mir geht es zumindest so bei meinen 20+ Adaptern. Anschließend musst Du nur noch die Adapterinstanzen manuell starten.

Wenn der neue ioBroker online ist, kannst Du den privaten DNS-Eintrag, den Du hoffentlich für den Zugriff nutzt, auf den neuen Host zeigen lassen. Den alten Container kannst Du jetzt erst einmal anhalten; wenn der neue ioBroker nicht richtig funktionert, startest Du einfach den alten wieder. ;-) 

Diese Vorgehensweise hat bei mir schon für tiefenentspannte Abende gesorgt, da ich meiner Familie nicht mehr erklären musste, dass die Steuerung der Beleuchtung, etc. grad nicht mit der Sprachassistentin möglich ist, da ja noch das Update läuft. Dinge, die vermeintlich niemand braucht nach Aussage meiner Familie wie Sprachsteuerung, automatische Beleuchtungsregelung, etc. sind dann ganz plötzlich unverzichtbar. Aber wie gesagt, das Thema habe ich nicht mehr, seitdem ich immer parallel aufbaue und dann die alte Instanz ausschalte. Klappt wunderbar.

Ich hoffe, das kann Dir als Anhaltspunkt dienen.

**Comment by BeSiRe1** [comment]
Alles klar. Danke dir.

**Comment by ali86x** [comment]
Heute leider wieder selber Fehler.

**Comment by MiGoller** [comment]
Störung vom 20./21.12.2023 wird in #83 behandelt.
