### ISSUE TITLE
Keine Sonderzeichen im Passwort

### ISSUE THREAD

**Issue by BeSiRe1** [MiGoller/ioBroker.life360#81]
Hallo,

mein Email Account wurde gehackt und so bin ich gezwungen alle Passwörter zu ändern.
Damit das in Zukunkt nicht mehr passiert habe ich sehr langes Passwort mit Sonderzeichen gewählt.
Sonderzeichen sind ( ) , :    
Leider nimmt der Adapter diese anscheinend nicht.

Adapterversion 0.2.21

**Comment by MiGoller** [comment]
Hey, das werde ich prüfen. Die Sonderzeichen gehen in der mobilen App aber, oder?

**Comment by BeSiRe1** [comment]
Hey, ja Sonderzeichen gehen in der App.
Konnte mich jetzt aber auch im Adapter damit anmelden.
Also alles gut.

**Comment by MiGoller** [comment]
Dann schließe ich diesen Vorgang.
