### ISSUE TITLE
Life360 Adapter shows warning "Life360 circle data expected but missing!" - No objects were created

### ISSUE THREAD

**Issue by muehli-apps** [MiGoller/ioBroker.life360#82]
I've installed the Life360 Adapter. The login seems to work but then I get the following 2 warnings:
- Life360 circle data expected but missing!
- No circle data received from Life360. Aborting.

No people objects were created.

![image](https://github.com/MiGoller/ioBroker.life360/assets/121481913/b5af9748-01a0-45b8-af05-319db0d69c0e)
![image](https://github.com/MiGoller/ioBroker.life360/assets/121481913/972980fe-2fd7-4428-8100-9a35107db157)

**Comment by MiGoller** [comment]
Please update to v0.2.21 for a fix.
