### ISSUE TITLE
Life360 Keine Anmeldung möglich 

### ISSUE THREAD

**Issue by JacklBirgit** [MiGoller/ioBroker.life360#84]
Die Verbindung wurde hergestellt, die Authentifizierung konnte jedoch nicht durchgeführt werden. Überprüfen Sie Ihre Anmeldedaten!

**Comment by ChristophsMowL** [comment]
Same here:

Error: Error: Connection established but failed to authenticate. Check your credentials!

life360.0 | 2023-12-21 07:33:55.986 | error | Failed to connect or to login for 6 times. Aborting ...

credentials checked correctly

**Comment by MiGoller** [comment]
Duplicate of #83 . Will close this issue.
