### ISSUE TITLE
2023-12-28 19:24:39.194 - error: life360.0 (183651) Connection established but failed to authenticate. Check your credentials!

### ISSUE THREAD

**Issue by JacklBirgit** [MiGoller/ioBroker.life360#87]
Seit gestern wieder keine Verbindung.
life360 version 0.2.22
nodejs: 18.19.0
js-controller: 5.0.17

**Comment by MiGoller** [comment]
Hey @JacklBirgit , das tut mir leid. Ich kann es derzeit nicht nachvollziehen. Meine Instanzen laufen (noch) ohne Fehler.

Hast Du schon Dein Kennwort geändert? Melde Dich bitte mal in der Life360 App auf dem Smartphone ab und versuche dann, Dich mit Deinem aktuellen Kennwort anzumelden. Mich würde interessieren, ob das noch geht. Ich habe viel Feedback bekommen, dass in der App bei dem gleichen Fehlerbild dann der Hinweis kam, das Kennwort sei nicht komplex genug oder abgelaufen. Mit einem neuen Kennwort funktionierten dann die App und auch der Adapter wieder.

**Comment by JacklBirgit** [comment]
Hi, okay werde ich machen. Hat mich ein bisschen abgeschreckt. Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: MiGoller ***@***.***> Datum: 28.12.23  20:05  (GMT+01:00) An: "MiGoller/ioBroker.life360" ***@***.***> Cc: JacklBirgit ***@***.***>, Mention ***@***.***> Betreff: Re: [MiGoller/ioBroker.life360] 2023-12-28 19:24:39.194 - error: life360.0 (183651) Connection established but failed to authenticate. Check your credentials! (Issue #87) 
Hey @JacklBirgit , das tut mir leid. Ich kann es derzeit nicht nachvollziehen. Meine Instanzen laufen (noch) ohne Fehler.
Hast Du schon Dein Kennwort geändert? Melde Dich bitte mal in der Life360 App auf dem Smartphone ab und versuche dann, Dich mit Deinem aktuellen Kennwort anzumelden. Mich würde interessieren, ob das noch geht. Ich habe viel Feedback bekommen, dass in der App bei dem gleichen Fehlerbild dann der Hinweis kam, das Kennwort sei nicht komplex genug oder abgelaufen. Mit einem neuen Kennwort funktionierten dann die App und auch der Adapter wieder.

**Comment by splizz1st** [comment]
Ich hatte die gleichen Probleme und habe mich in der App ausgeloggt. Beim Einloggen kam die Info, dass mein Passwort abgelaufen ist. Neu vergeben und nun ist der Adapter wieder grün. Danke dir!!!

**Comment by JacklBirgit** [comment]
Mittlerweile habe ich das alles so gemacht wie beschrieben.
Alles funktioniert einwandfrei. Ich bedanke mich für die Hilfe und wünsche
allen einen guten Rutsch ins neue Jahr.

splizz1st ***@***.***> schrieb am Fr., 29. Dez. 2023, 08:40:

**Comment by MiGoller** [comment]
Danke für das Feedback. Ich schließe den Vorgang dann mit dem Verweis auf den von vor ein paar Tagen.

Dir auch einen guten Rutsch,

**Comment by MiGoller** [comment]
Duplicate to #86
