### ISSUE TITLE
check Adapter with js-controller 3.0.x 

### ISSUE THREAD

**Issue by Ilovegym66** [MiGoller/ioBroker.life360#9]
Hi,
check the Adapter with js-controller 3.0.x, please. 
System, Linux Buster, Node 12, js-controller 3.0.7
`

life360.0 | 2020-04-13 12:24:02.841 | warn | (10030) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
life360.0 | 2020-04-13 12:24:02.840 | warn | (10030) Object life360.0.info.connection is invalid: obj.common.read  has an invalid type! Expected "boolean", received  "string"

`

**Comment by MiGoller** [comment]
Hey,

thank you for reporting that warning. I'll have a look at those issues.

Regards,
Michael

**Comment by MiGoller** [comment]
Hey,

I do expect a "boolean" value, too. Can you tell me the `life360.0.info.connection` datapoint's value and definition of your setup, please? Inspect the datapoint's raw view to check the definition of `common`. My datapoint's `common` attribute looks like this:
```
"common": {
    "name": "connected",
    "desc": "Connected to Life360 cloud services?",
    "type": "boolean",
    "def": false,
    "read": true,
    "role": "value.info",
    "write": false
  }
```
Can you confirm?

Regards,
Michael

**Comment by Ilovegym66** [comment]
{
  "_id": "life360.0.info.connection",
  "type": "state",
  "common": {
    "name": "connected",
    "desc": "Connected to Life360 cloud services?",
    "type": "boolean",
    "def": "false",
    "read": "true",
    "role": "value.info",
    "write": "false"
  },
  "native": {},
  "from": "system.host.iobroker.cli",
  "ts": 1580741884198,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by MiGoller** [comment]
Hey,

thank you very much. Will have to update the `instanceObjects` section to create datapoints on adapter startup in the correct manner: The definition does not allow anymore boolean values typed as string. `"true"`--> `true` without the quotes.

Will fix that.

Best Regards, Michael
